groups:
  - name: Exporter Alerts
    rules:
      - alert: MariadbExporterCaido
        expr: up{job="mariadb"} == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: El Exportador de MariaDB está caído
          description: El Exportador de MariaDB ha estado caído por más de 1 minuto. xxxx
          
  - name: CPU Usage Alerts
    rules:
      - alert: HighCPUUsageMariadbExporter
        expr: >-
          avg(rate(process_cpu_seconds_total{instance="mariadb-exporter:9104"}[5m])
          * 1000) > 80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Alto uso de CPU en el Exportador de MariaDB
          description: >-
            El uso promedio de CPU en el Exportador de MariaDB ha superado el
            80% en los últimos 5 minutos.
  - name: Memory Usage Alerts
    rules:
      - alert: HighMemoryUsageMariadbExporter
        expr: >-
          avg(rate(process_resident_memory_bytes{instance="mariadb-exporter:9104"}[5m]))
          > 500 * 1024 * 1024
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Alto uso de memoria en el Exportador de MariaDB
          description: >-
            El uso promedio de RAM en el Exportador de MariaDB ha superado los
            500 MB en los últimos 5 minutos.
  - name: Active Connections Alerts
    rules:
      - alert: HighActiveConnectionsMySQL
        expr: mysql_global_status_threads_running > 50
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Muchas conexiones activas en MySQL
          description: >-
            El número de conexiones activas en MySQL ha superado las 50 en los
            últimos 60 segundos.
  - name: Open File Descriptors Alerts
    rules:
      - alert: HighOpenFileDescriptorsMariaDB
        expr: process_open_fds{instance="mariadb-exporter:9104"} > 1000
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Alto número de File Descriptors abiertos en MariaDB Exporter
          description: >-
            El número de File Descriptors abiertos por el exportador de MariaDB
            ha superado los 1000 en los últimos 60 segundos.
  - name: MariaDB Operations Alerts
    rules:
      - alert: HighDeleteOperationsMySQL
        expr: rate(mysql_global_status_commands_total{command="delete"}[5m]) > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Alto número de operaciones de eliminación en MySQL
          description: >-
            Se han detectado más de 100 operaciones de eliminación por segundo
            en MySQL en los últimos 5 minutos.
      - alert: HighUpdateOperationsMySQL
        expr: rate(mysql_global_status_commands_total{command="update"}[5m]) > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Alto número de operaciones de actualización en MySQL
          description: >-
            Se han detectado más de 100 operaciones de actualización por segundo
            en MySQL en los últimos 5 minutos.
      - alert: HighInsertOperationsMySQL
        expr: rate(mysql_global_status_commands_total{command="insert"}[5m]) > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Alto número de operaciones de inserción en MySQL
          description: >-
            Se han detectado más de 100 operaciones de inserción por segundo en
            MySQL en los últimos 5 minutos.
            
  - name: Data Rate Alerts
    rules:
      - alert: HighDataReceivedRateMySQL
        expr: rate(mysql_global_status_bytes_received[5m]) > 1e6
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Alta tasa de datos recibidos en MySQL
          description: >-
            Se ha detectado una tasa de más de 1 MB por segundo de datos
            recibidos en MySQL en los últimos 5 minutos. Verifica si esta carga
            es esperada.
      - alert: HighDataSentRateMySQL
        expr: rate(mysql_global_status_bytes_sent[5m]) > 1e6
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Alta tasa de datos enviados en MySQL
          description: >-
            Se ha detectado una tasa de más de 1 MB por segundo de datos
            enviados en MySQL en los últimos 5 minutos. Verifica si esta carga
            es normal.