groups:
  - name: AlertasDelExportador
    rules:
      - alert: ExportadorDeMongoCaido
        expr: up{job="mongo"} == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: ElExportadorDeMongoEstaCaido
          description: El exportador de Mongo ha estado caído por más de 1 minuto.
  - name: AlertasUsoDeCPU
    rules:
      - alert: ExportadorAltoUsoDeCPUMongoDB
        expr: >-
          avg(rate(process_cpu_seconds_total{instance="mongo-exporter:9216"}[5m])
          * 1000) > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: AltoUsoDeCPUEnElExportadorDeMongo
          description: >-
            El uso promedio de CPU en el exportador de Mongo ha superado el 5%
            en los últimos 5 minutos.
  - name: AlertasUsoDeMemoria
    rules:
      - alert: ExportadorAltoUsoDeMemoriaMongoDB
        expr: >-
          avg(rate(process_resident_memory_bytes{instance="mongo-exporter:9216"}[5m]))
          > 1 * 1024 * 1024
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: AltoUsoDeMemoriaEnElExportadorDeMongo
          description: >-
            El uso promedio de RAM en el exportador de Mongo ha superado 1 MB
            en los últimos 5 minutos.
  - name: AlertasConexionesActivas
    rules:
      - alert: ConexionesActivasAltasMongoDB
        expr: >-
          mongodb_connections{instance="mongo-exporter:9216", state="current"} > 3
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: MuchasConexionesActivasEnMongoDB
          description: >-
            El número de conexiones activas en MongoDB ha superado las 3
            en los últimos 60 segundos.
  - name: AlertasFileDescriptorsAbiertos
    rules:
      - alert: FileDescriptorsAbiertosAltosMongoDB
        expr: process_open_fds{instance="mongo-exporter:9216"} > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: AltoNumeroDeFileDescriptorsAbiertosEnMongoDBExportador
          description: >-
            El número de File Descriptors abiertos por el exportador de MongoDB
  - name: AlertasOperacionesMongoDB
    rules:
      - alert: OperacionesDeEliminacionAltasMongoDB
        expr: mongodb_op_counters_total{type="delete"} > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: AltoNumeroDeOperacionesDeEliminacionEnMongoDB
          description: >-
            Se han detectado más de 100 operaciones de eliminación 
            en MongoDB 
      - alert: OperacionesDeActualizacionAltasMongoDB
        expr: mongodb_op_counters_total{type="update"} > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: AltoNumeroDeOperacionesDeActualizacionEnMongoDB
          description: >-
            Se han detectado más de 100 operaciones de actualización en MongoDB
      - alert: OperacionesDeInsercionAltasMongoDB
        expr: mongodb_op_counters_total{type="insert"} > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: AltoNumeroDeOperacionesDeInsercionEnMongoDB
          description: >-
            Se han detectado más de 100 operaciones de inserción en MongoDB