{
 "title": "Postgres + Maria + Mongo",
 "tags": [
  "postgres",
  "mariabd",
  "mongodb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Promedio de Uso de RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"postgres-exporter:9187\"}[5m]))",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "MariaDB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"mariadb-exporter:9104\"}[5m]))",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"mongo-exporter:9216\"}[5m]))",
     "legendFormat": "RAM"
    }
   ]
  },
  { "title": "Promedio de Uso de CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"postgres-exporter:9187\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "MariaDB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"mariadb-exporter:9104\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"mongo-exporter:9216\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  { "title": "Open File Descriptors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "PostgreSQL",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"postgres-exporter:9187\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "MariaDB",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"mariadb-exporter:9104\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"mongo-exporter:9216\"}",
     "legendFormat": "Open FD"
    }
   ]
  }
 ]
}