{
 "title": "Postgres + Mongo",
 "tags": [
  "postgres",
  "mariabd",
  "mongodb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } }
  ]
 },
 "panels": [
  { "title": "Estado del servidor ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Postgres",
   "type": "stat",
   "description": "Estado del servidor",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "Postgres" }
   ]
  },
  {
   "title": "MongoDB",
   "type": "stat",
   "description": "Estado del servidor",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_up", "legendFormat": "Mongo" }
   ]
  },
  { "title": "Promedio de Uso de CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"postgres-exporter:9187\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"mongo-exporter:9216\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  { "title": "Promedio de Uso de RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"postgres-exporter:9187\"}[5m]))",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"mongo-exporter:9216\"}[5m]))",
     "legendFormat": "RAM"
    }
   ]
  },
  { "title": "Conexiones Activas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{job=\"postgres\",state=\"active\"} !=0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mongo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{instance=\"mongo-exporter:9216\", state=\"current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Open File Descriptors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 } },
  {
   "title": "MongoDB",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"mongo-exporter:9216\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Errores de consulta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "description": "Número de conflictos en la base de datos que resultaron en cancelaciones de consultas.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "pg_stat_database_conflicts", "legendFormat": "{{datname}}" }
   ]
  },
  {
   "title": "MongoDB",
   "type": "timeseries",
   "description": "Registra el número total de \"asserts\" (errores y advertencias) que han ocurrido en la instancia de MongoDB, categorizados por tipo. Los \"asserts\" representan eventos que pueden indicar problemas en la operación de la base de datos. Esta métrica es útil para identificar patrones de errores y advertencias recurrentes que podrían afectar el desempeño o la estabilidad.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "mongodb_asserts_total", "legendFormat": "{{type}}" }
   ]
  },
  { "title": "Operaciones de Eliminaciones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_del[$__rate_interval])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "mongodb_op_counters_total{type=\"delete\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Operaciones de Actualizaciones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_upd[$__rate_interval])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "mongodb_op_counters_total{type=\"update\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Operaciones de escritura ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "targets": [
    { "expr": "pg_stat_user_tables_n_tup_ins", "legendFormat": "{{relname}}" }
   ]
  },
  {
   "title": "MongoDB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "mongodb_op_counters_total{type=\"insert\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Tasa de transacciones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "description": "Mide la tasa de transacciones confirmadas (xact_commit) y revertidas (xact_rollback) en PostgreSQL durante los últimos 5 minutos, permitiendo monitorear el desempeño y los conflictos en las transacciones de la base de datos.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{datname=~\"$datname\", instance=\"postgres-exporter:9187\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{datname=~\"$datname\", instance=\"postgres-exporter:9187\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "timeseries",
   "description": "Calcula la tasa de transacciones que han sido confirmadas (committed) en el motor de almacenamiento WiredTiger de MongoDB durante los últimos 5 minutos. Esta métrica refleja el flujo de transacciones exitosas y es útil para monitorear la carga transaccional y el desempeño del sistema.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "irate(mongodb_mongod_wiredtiger_transactions_total{type=\"committed\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(mongodb_mongod_wiredtiger_transactions_total{type=\"rolledback\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Tasas de datos recibidas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "description": "calcula la tasa promedio de filas devueltas por segundo desde la base de datos PostgreSQL hacia los clientes durante los últimos 5 minutos.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "timeseries",
   "description": "calcula la tasa promedio de bytes recibidos por segundo por el servidor MongoDB desde los clientes en los últimos 5 minutos.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{state=\"in_bytes\"}[5m])",
     "legendFormat": "Bytes recibidos"
    }
   ]
  },
  { "title": "Tasas de bytes enviadas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "description": "mide el número total de bloques leídos desde el disco por las consultas ejecutadas en una base de datos PostgreSQL.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pg_stat_database_blks_read", "legendFormat": "{{datname}}" }
   ]
  },
  {
   "title": "MongoDB",
   "type": "timeseries",
   "description": "alcula la tasa promedio de bytes enviados por segundo desde un servidor MongoDB hacia los clientes durante los últimos 5 minutos.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{state=\"out_bytes\"}[5m])",
     "legendFormat": "Bytes enviados"
    }
   ]
  }
 ]
}