{
 "title": "Postgres + MariaDB",
 "tags": [
  "mariadb",
  "postgres"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } }
  ]
 },
 "panels": [
  { "title": "Estado del Servidor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Postgres",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MariaDB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  { "title": "Conexiones Activas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Postgres",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{job=\"postgres\",state=\"active\"} !=0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MariaDB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_running",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Promedio de Uso de RAM ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"postgres-exporter:9187\"}[5m]))",
     "legendFormat": "RAM"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MariaDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"mariadb-exporter:9104\"}[5m]))",
     "legendFormat": "RAM"
    }
   ]
  },
  { "title": "Promedio de Uso de CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"postgres-exporter:9187\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "MariaDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"mariadb-exporter:9104\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  { "title": "Archivos abiertos DF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "PostgreSQL",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"postgres-exporter:9187\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "MariaDB",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"mariadb-exporter:9104\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Errores de Consulta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "description": "Número de conflictos en la base de datos que resultaron en cancelaciones de consultas.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_conflicts[$__rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "MariaDB",
   "type": "timeseries",
   "description": "Número de consultas que han tardado más de lo esperado en ejecutarse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "mysql_global_status_slow_queries",
     "legendFormat": "MariaDB"
    }
   ]
  },
  { "title": "Operaciones de Eliminación ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_del[$__rate_interval])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "MariaDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total{command=\"delete\"}",
     "legendFormat": "{{command}}"
    }
   ]
  },
  { "title": "Operaciones de Actualización ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_upd[$__rate_interval])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "MariaDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total{command=\"update\"}",
     "legendFormat": "{{command}}"
    }
   ]
  },
  { "title": "Operaciones de Escritura", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    { "expr": "pg_stat_user_tables_n_tup_ins", "legendFormat": "{{relname}}" }
   ]
  },
  {
   "title": "MariaDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total{command=\"insert\"}",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Tasa de Transacciones",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postgres",
     "type": "timeseries",
     "description": "Mide la tasa de transacciones confirmadas (xact_commit) y revertidas (xact_rollback) en PostgreSQL durante los últimos 5 minutos, permitiendo monitorear el desempeño y los conflictos en las transacciones de la base de datos.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "irate(pg_stat_database_xact_commit{datname=~\"$datname\", instance=\"postgres-exporter:9187\"}[5m])",
       "legendFormat": "{{datname}} commits"
      },
      {
       "expr": "irate(pg_stat_database_xact_rollback{datname=~\"$datname\", instance=\"postgres-exporter:9187\"}[5m])",
       "legendFormat": "{{datname}} rollbacks"
      }
     ]
    },
    {
     "title": "MariaDB",
     "type": "timeseries",
     "description": "Calcula la tasa de transacciones confirmadas (commit) y revertidas (rollback) en MySQL durante los últimos 5 minutos, proporcionando una visión clara del flujo de transacciones exitosas y fallidas en el sistema.\n\n\n\n\n\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_commands_total{command=\"commit\"}[5m])",
       "legendFormat": "{{datname}} commits"
      },
      {
       "expr": "irate(mysql_global_status_commands_total{command=\"rollback\"}[5m])",
       "legendFormat": "{{command}}"
      }
     ]
    }
   ]
  },
  { "title": "Tasa de datos recibidas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "description": "calcula la tasa promedio de filas devueltas por segundo desde la base de datos PostgreSQL hacia los clientes durante los últimos 5 minutos.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "MariaDB",
   "type": "timeseries",
   "description": "describe la tasa promedio de bytes recibidos por segundo desde el servidor MySQL hacia los clientes en un intervalo de 5 minutos.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received[5m])",
     "legendFormat": "Bytes recibidos"
    }
   ]
  },
  { "title": "Tasa de datos enviados", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "description": "mide el número total de bloques leídos desde el disco por las consultas ejecutadas en una base de datos PostgreSQL.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pg_stat_database_blks_read", "legendFormat": "{{datname}}" }
   ]
  },
  {
   "title": "MariaDB",
   "type": "timeseries",
   "description": "describe la tasa promedio de bytes recibidos por segundo desde el servidor MySQL hacia los clientes en un intervalo de 5 minutos.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received[5m])",
     "legendFormat": "Bytes recibidos"
    }
   ]
  }
 ]
}