{
 "title": "Maria + Mongo",
 "tags": [
  "mongodb",
  "mariadb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } }
  ]
 },
 "panels": [
  {
   "title": "Tasa de transacciones",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "MariaDB", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 } },
    { "title": "MariaDB", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 } }
   ]
  },
  {
   "title": "Estado del Servidor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postgres",
     "type": "stat",
     "description": "Estado del servidor",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mysql_up", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Postgres",
     "type": "stat",
     "description": "Estado del servidor",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mongodb_up", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Conexiones Activas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "MariaDB",
     "type": "stat",
     "description": "Conexiones activas",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_status_threads_running",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MongoDB",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_connections{instance=\"mongo-exporter:9216\", state=\"current\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Promedio de Uso de CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    { "title": "MariaDB", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 72 } },
    { "title": "MariaDB", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 72 } }
   ]
  },
  {
   "title": "Promedio de Uso de RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    { "title": "PostgreSQL", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 } },
    { "title": "PostgreSQL", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 } }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    { "title": "PostgreSQL", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 } },
    { "title": "PostgreSQL", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 } }
   ]
  },
  {
   "title": "Errores en consultas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "MariaDB",
     "type": "timeseries",
     "description": "Cuenta el número de consultas marcadas como lentas porque superaron el tiempo configurado. ",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "mysql_global_status_slow_queries",
       "legendFormat": "Consultas lentas"
      }
     ]
    },
    {
     "title": "MongoDB",
     "type": "timeseries",
     "description": "Registra el número total de \"asserts\" (errores y advertencias) que han ocurrido en la instancia de MongoDB, categorizados por tipo. Los \"asserts\" representan eventos que pueden indicar problemas en la operación de la base de datos. Esta métrica es útil para identificar patrones de errores y advertencias recurrentes que podrían afectar el desempeño o la estabilidad.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "targets": [
      { "expr": "mongodb_asserts_total", "legendFormat": "{{type}}" }
     ]
    }
   ]
  },
  {
   "title": "Operaciones de Inserción ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "MariaDB",
     "type": "timeseries",
     "description": "Insert\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "mysql_global_status_commands_total{command=\"insert\"}",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "MongoDB",
     "type": "timeseries",
     "description": "Insert\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "mongodb_op_counters_total{type=\"insert\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operaciones de Actualización ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "MariaDB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "mysql_global_status_commands_total{command=\"update\"}",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "MongoDB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "mongodb_op_counters_total{type=\"update\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operaciones de Eliminación ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    { "title": "MariaDB", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 } },
    { "title": "MariaDB", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 } }
   ]
  },
  {
   "title": "Tasa de bytes recibidos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    { "title": "MariaDB", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 } },
    { "title": "MariaDB", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 } }
   ]
  },
  {
   "title": "Tasa de bytes enviados",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    { "title": "MariaDB", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 } },
    { "title": "MariaDB", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 } }
   ]
  }
 ]
}